render_dataset:
  _target_: run_render.BaseRenderDataset
  subject: S9
  h5_path: data/h36m_zju/${.subject}_anim.h5
  idxs: np.arange(84)
  resolution: [1000, 1000]
  cam_overwrite: -1


model_config: ???
output_path: ???